name: Test Flask App

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Start the Flask development server
      run: python app.py &

    - name: Wait for server to start up
      run: |
        sleep 10

    - name: Test APIs
      run: |
        curl -X GET http://localhost:5000
        curl -X GET http://localhost:5000/form
        curl http://localhost:5000//download_weights/0
    
    - name: Run Tests for CPU model testing
      run: |
        pytest test.py
